# Generated by Django 4.0.4 on 2022-06-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_createcurrency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcurrency',
            old_name='suffix_to_amouny',
            new_name='suffix_to_amount',
        ),
        migrations.AddField(
            model_name='createcurrency',
            name='decimal_places',
            field=models.IntegerField(default=3),
        ),
    ]
