# Generated by Django 4.0.4 on 2022-06-21 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_vouchermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAlter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slno', models.CharField(max_length=225)),
                ('currencys', models.CharField(max_length=225)),
                ('stdrate', models.CharField(max_length=225)),
                ('lastvrate', models.CharField(max_length=225)),
                ('specirate', models.CharField(max_length=225)),
                ('lastvrate2', models.CharField(max_length=225)),
                ('specirate2', models.CharField(max_length=225)),
                ('cname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.createcurrency')),
            ],
        ),
    ]
