# Generated by Django 4.0.4 on 2022-06-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_currencyalter'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcurrency',
            name='flag',
            field=models.CharField(default=0, max_length=225),
        ),
    ]
