# Generated by Django 4.0.4 on 2022-06-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_limit', models.CharField(max_length=225)),
                ('holder_name', models.CharField(max_length=225)),
                ('ac_number', models.CharField(max_length=225)),
                ('ifsc', models.CharField(max_length=225)),
                ('swift_code', models.CharField(max_length=225)),
                ('bank_name', models.CharField(max_length=225)),
                ('branch_name', models.CharField(max_length=225)),
                ('alter_chk_bks', models.BooleanField()),
                ('enbl_chk_printing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LedgerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.CharField(max_length=225)),
                ('ledger_alias', models.CharField(max_length=225)),
                ('ledger_opening_bal', models.CharField(max_length=225)),
                ('ledger_type', models.CharField(max_length=225)),
                ('type_of_duty', models.CharField(max_length=225)),
                ('percent_of_calculation', models.CharField(max_length=225)),
                ('maintain_bal_bill', models.CharField(max_length=225)),
                ('credit_days_during_voucher_entry', models.CharField(max_length=225)),
                ('default_cr_peroid', models.CharField(max_length=225)),
                ('provide_banking_details', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LedgerSatutoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessable_calculation', models.CharField(max_length=225)),
                ('gst_applicable', models.CharField(max_length=225)),
                ('type_of_supply', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MailingAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('state', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('pincode', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_uin', models.CharField(max_length=225)),
                ('register_type', models.CharField(max_length=225)),
                ('pan_no', models.CharField(max_length=225)),
                ('alter_gst_details', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VoucherModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('voucher_type', models.CharField(max_length=225)),
                ('abbreviation', models.CharField(max_length=225)),
                ('active_this_voucher_type', models.CharField(max_length=225)),
                ('method_voucher_numbering', models.CharField(max_length=225)),
                ('use_adv_conf', models.CharField(max_length=225)),
                ('prvnt_duplictes', models.CharField(default='Null', max_length=225)),
                ('use_effective_date', models.CharField(default='Null', max_length=225)),
                ('allow_zero_value_trns', models.CharField(max_length=225)),
                ('allow_naration_in_voucher', models.CharField(max_length=225)),
                ('make_optional', models.CharField(max_length=225)),
                ('provide_naration', models.CharField(max_length=225)),
                ('print_voucher', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='VoucherModel',
        ),
    ]
