# Generated by Django 4.0 on 2022-07-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_banking_details_companymodel_ledger_ledger_rounding_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banking_Details',
            new_name='Ledger_Banking_Details',
        ),
        migrations.RenameModel(
            old_name='Mailing_Address',
            new_name='Ledger_Mailing_Address',
        ),
        migrations.RenameModel(
            old_name='Tax_Register',
            new_name='Ledger_Tax_Register',
        ),
    ]
