# Generated by Django 4.0.4 on 2022-07-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_banking_details_ledger_banking_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='does_it_affect',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='nature_of_group',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
    ]
