# Generated by Django 4.0.4 on 2022-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_groupmodel_does_it_affect_groupmodel_nature_of_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='under',
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='alias',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='gp_behaves_like_sub_ledger',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='method_to_allocate_usd_purchase',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='nett_debit_credit_bal_reporting',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='used_for_calculation',
            field=models.CharField(blank=True, default='Null', max_length=225),
        ),
    ]
